import {JsonColumn, JsonEnum, JsonForeignKey, JsonIndex, JsonIndexType, JsonRoutine, JsonRoutineKind, JsonTable, JsonView} from '../../DbEditor/JsonData.js';
import {DbDialect, DialectContext} from '../DbDialect.js';

/**
 * PostgreSQL DDL renderer. Identifiers are double-quoted, ENUMs are
 * declared as separate types via CREATE TYPE, AUTO_INCREMENT becomes
 * `GENERATED BY DEFAULT AS IDENTITY` (modern; SERIAL is also accepted),
 * and table options like ENGINE / CHARSET are ignored.
 */
export class PostgresDialect implements DbDialect {

    public quote(name: string): string {
        return `"${  name.replace(/"/gu, '""')  }"`;
    }

    public mapColumnType(col: JsonColumn, ctx: DialectContext): string {
        const t = (col.type || '').toLowerCase();
        const len = col.length ? `(${col.length})` : '';
        switch (t) {
            case 'tinyint':
            case 'smallint':  return 'SMALLINT';
            case 'mediumint':
            case 'int':
            case 'integer':   return col.autoIncrement ? 'INTEGER' : 'INTEGER';
            case 'bigint':    return 'BIGINT';
            case 'bool':
            case 'boolean':   return 'BOOLEAN';
            case 'decimal':
            case 'numeric':   return `NUMERIC${len || '(10,0)'}`;
            case 'float':     return 'REAL';
            case 'double':    return 'DOUBLE PRECISION';
            case 'char':      return `CHAR${len || '(1)'}`;
            case 'varchar':   return `VARCHAR${len || '(255)'}`;
            case 'tinytext':
            case 'text':
            case 'mediumtext':
            case 'longtext':  return 'TEXT';
            case 'blob':
            case 'longblob':
            case 'binary':
            case 'varbinary': return 'BYTEA';
            case 'json':      return 'JSONB';
            case 'uuid':      return 'UUID';
            case 'date':      return 'DATE';
            case 'time':      return `TIME${len}`;
            case 'datetime':
            case 'timestamp': return `TIMESTAMP${len}`;
            case 'year':      return 'SMALLINT';
            case 'enum': {
                if (!col.enumRef) {return 'TEXT';}
                const e = ctx.findEnum(col.enumRef);
                if (!e) {return 'TEXT';}
                return this.quote(e.name);
            }
            default:
                return col.length ? `${col.type.toUpperCase()}(${col.length})` : col.type.toUpperCase();
        }
    }

    protected renderColumnFlags(col: JsonColumn): string {
        const parts: string[] = [];
        if (col.notNull) {parts.push('NOT NULL');}
        if (col.autoIncrement) {parts.push('GENERATED BY DEFAULT AS IDENTITY');}
        if (col.defaultValue !== undefined && col.defaultValue !== '' && !col.autoIncrement) {
            parts.push(`DEFAULT ${col.defaultValue}`);
        }
        if (col.unique && !col.primaryKey) {parts.push('UNIQUE');}
        return parts.join(' ');
    }

    public renderCreateTable(table: JsonTable, ctx: DialectContext): string {
        const lines: string[] = [];
        for (const col of table.columns) {
            const type = this.mapColumnType(col, ctx);
            const flags = this.renderColumnFlags(col);
            lines.push(`${ctx.indent}${this.quote(col.name)} ${type}${flags ? ` ${  flags}` : ''}`);
        }
        const pkCols = table.columns.filter(c => c.primaryKey);
        if (pkCols.length) {
            lines.push(`${ctx.indent}PRIMARY KEY (${pkCols.map(c => this.quote(c.name)).join(', ')})`);
        }

        const o = table.options || {};
        const persistence = o.persistence ? `${o.persistence.toUpperCase()} ` : '';
        const head = `CREATE ${persistence}TABLE ${this.quote(table.name)} (\n`;
        const tail = '\n)';
        let stmt = head + lines.join(',\n') + tail;
        if (o.tablespace) {stmt += ` TABLESPACE ${this.quote(o.tablespace)}`;}
        return stmt;
    }

    public renderCreateIndex(table: JsonTable, ix: JsonIndex, ctx: DialectContext): string | null {
        if (!ix.columns.length) {return null;}
        const cols = ix.columns.map(ic => {
            const c = ctx.findColumn(table.unid, ic.columnUnid);
            if (!c) {return '';}
            const order = ic.order && ic.order.toUpperCase() === 'DESC' ? ' DESC' : '';
            return `${this.quote(c.name)}${order}`;
        }).filter(Boolean).join(', ');
        const t = (ix.type || JsonIndexType.index).toLowerCase();
        const unique = t === JsonIndexType.unique ? 'UNIQUE ' : '';
        const usingMap: Record<string, string> = {
            [JsonIndexType.fulltext]: ' USING GIN',
            [JsonIndexType.spatial]: ' USING GIST'
        };
        const using = usingMap[t] ?? '';
        const where = ix.where ? ` WHERE ${ix.where}` : '';
        return `CREATE ${unique}INDEX ${this.quote(ix.name)} ON ${this.quote(table.name)}${using} (${cols})${where}`;
    }

    public renderAddForeignKey(table: JsonTable, fk: JsonForeignKey, ctx: DialectContext): string | null {
        const ref = ctx.findTable(fk.refTableUnid);
        if (!ref) {return null;}
        const localCols: string[] = [];
        const refCols: string[] = [];
        for (const fc of fk.columns) {
            const local = ctx.findColumn(table.unid, fc.columnUnid);
            const remote = ctx.findColumn(ref.unid, fc.refColumnUnid);
            if (!local || !remote) {return null;}
            localCols.push(this.quote(local.name));
            refCols.push(this.quote(remote.name));
        }
        const onDelete = fk.onDelete ? ` ON DELETE ${fk.onDelete}` : '';
        const onUpdate = fk.onUpdate ? ` ON UPDATE ${fk.onUpdate}` : '';
        return `ALTER TABLE ${this.quote(table.name)} `
            + `ADD CONSTRAINT ${this.quote(fk.name)} `
            + `FOREIGN KEY (${localCols.join(', ')}) `
            + `REFERENCES ${this.quote(ref.name)} (${refCols.join(', ')})${onDelete}${onUpdate}`;
    }

    public renderCreateEnum(e: JsonEnum, _ctx: DialectContext): string | null {
        if (!e.values.length) {return null;}
        const values = e.values.map(v => `'${v.value.replace(/'/gu, '\'\'')}'`).join(', ');
        return `CREATE TYPE ${this.quote(e.name)} AS ENUM (${values})`;
    }

    public renderDropTable(table: JsonTable, _ctx: DialectContext): string {
        return `DROP TABLE IF EXISTS ${this.quote(table.name)} CASCADE`;
    }

    public renderDropIndex(_table: JsonTable, ix: JsonIndex, _ctx: DialectContext): string | null {
        return `DROP INDEX IF EXISTS ${this.quote(ix.name)}`;
    }

    public renderDropEnum(e: JsonEnum, _ctx: DialectContext): string | null {
        return `DROP TYPE IF EXISTS ${this.quote(e.name)}`;
    }

    public renderCreateView(view: JsonView, _ctx: DialectContext): string | null {
        const body = view.select.trim();
        if (!body) {return null;}
        /*
         * Postgres has no `CREATE OR REPLACE` for MATERIALIZED VIEW —
         * emit IF NOT EXISTS for materialized, OR REPLACE otherwise.
         */
        const head = view.materialized
            ? `CREATE MATERIALIZED VIEW IF NOT EXISTS ${this.quote(view.name)}`
            : `CREATE OR REPLACE VIEW ${this.quote(view.name)}`;
        return `${head} AS\n${body}`;
    }

    public renderDropView(view: JsonView, _ctx: DialectContext): string | null {
        const kind = view.materialized ? 'MATERIALIZED VIEW' : 'VIEW';
        return `DROP ${kind} IF EXISTS ${this.quote(view.name)}`;
    }

    /*
     * -----------------------------------------------------------------------
     * Sync-with-DB ALTER renderers
     *
     * Postgres splits column changes into multiple `ALTER COLUMN` clauses.
     * We compose them into one ALTER TABLE statement with comma-separated
     * actions so the executor sees ONE atomic DDL per change.
     * -----------------------------------------------------------------------
     */

    public renderAlterTableAddColumn(table: JsonTable, col: JsonColumn, ctx: DialectContext): string {
        const type = this.mapColumnType(col, ctx);
        const flags = this.renderColumnFlags(col);
        const colDef = `${this.quote(col.name)} ${type}${flags ? ` ${flags}` : ''}`;
        return `ALTER TABLE ${this.quote(table.name)} ADD COLUMN ${colDef}`;
    }

    public renderAlterTableDropColumn(table: JsonTable, col: JsonColumn, _ctx: DialectContext): string {
        return `ALTER TABLE ${this.quote(table.name)} DROP COLUMN ${this.quote(col.name)}`;
    }

    public renderAlterTableChangeColumn(table: JsonTable, oldCol: JsonColumn, newCol: JsonColumn, ctx: DialectContext): string {
        const actions: string[] = [];
        const q = this.quote(newCol.name);

        const oldType = this.mapColumnType(oldCol, ctx);
        const newType = this.mapColumnType(newCol, ctx);
        if (oldType !== newType) {
            /*
             * USING gives Postgres an explicit cast expression. We default
             * to the safe `<col>::<newtype>` which works for compatible
             * conversions; lossy conversions still require a manual
             * migration, which we can't help with from the diff alone.
             */
            actions.push(`ALTER COLUMN ${q} SET DATA TYPE ${newType} USING ${q}::${newType}`);
        }

        const oldDefault = oldCol.defaultValue ?? '';
        const newDefault = newCol.defaultValue ?? '';
        if (oldDefault !== newDefault) {
            if (newDefault === '') {
                actions.push(`ALTER COLUMN ${q} DROP DEFAULT`);
            } else {
                actions.push(`ALTER COLUMN ${q} SET DEFAULT ${newDefault}`);
            }
        }

        const oldNotNull = Boolean(oldCol.notNull);
        const newNotNull = Boolean(newCol.notNull);
        if (oldNotNull !== newNotNull) {
            actions.push(`ALTER COLUMN ${q} ${newNotNull ? 'SET NOT NULL' : 'DROP NOT NULL'}`);
        }

        if (actions.length === 0) {
            /*
             * Shouldn't happen — caller only invokes this when diff fields
             * are non-empty — but emit a no-op SQL just in case so the
             * executor doesn't choke on an empty string.
             */
            return `ALTER TABLE ${this.quote(table.name)} ALTER COLUMN ${q} DROP EXPRESSION IF EXISTS`;
        }

        return `ALTER TABLE ${this.quote(table.name)} ${actions.join(', ')}`;
    }

    public renderDropForeignKey(table: JsonTable, fkName: string, _ctx: DialectContext): string {
        return `ALTER TABLE ${this.quote(table.name)} DROP CONSTRAINT ${this.quote(fkName)}`;
    }

    public renderAlterTableOptions(table: JsonTable, _ctx: DialectContext): string | null {
        const o = table.options || {};
        const parts: string[] = [];
        /*
         * Postgres has no engine / charset / collation knobs at the table
         * level — those are global. Only `tablespace` and `persistence`
         * survive the trip, and even those need separate statement forms:
         *   ALTER TABLE x SET TABLESPACE ...
         *   ALTER TABLE x SET UNLOGGED   /   SET LOGGED
         */
        if (o.tablespace) {parts.push(`SET TABLESPACE ${this.quote(o.tablespace)}`);}
        if (o.persistence) {
            const p = o.persistence.toUpperCase();
            if (p === 'UNLOGGED') {parts.push('SET UNLOGGED');}
            else if (p === 'LOGGED') {parts.push('SET LOGGED');}
            /* TEMPORARY isn't ALTER-able; ignore. */
        }
        if (o.comment) {
            /*
             * COMMENT ON TABLE is a separate top-level statement, not an
             * ALTER TABLE clause. We emit it joined with a `; ` so it goes
             * out as one chained DDL through the executor's exec() call.
             */
            const esc = o.comment.replace(/'/gu, '\'\'');
            return parts.length
                ? `ALTER TABLE ${this.quote(table.name)} ${parts.join(', ')}; COMMENT ON TABLE ${this.quote(table.name)} IS '${esc}'`
                : `COMMENT ON TABLE ${this.quote(table.name)} IS '${esc}'`;
        }
        if (!parts.length) {return null;}
        return `ALTER TABLE ${this.quote(table.name)} ${parts.join(', ')}`;
    }

    public renderRenameTable(oldName: string, newName: string, _ctx: DialectContext): string | null {
        return `ALTER TABLE ${this.quote(oldName)} RENAME TO ${this.quote(newName)}`;
    }

    public renderRenameColumn(table: JsonTable, oldName: string, newCol: JsonColumn, _ctx: DialectContext): string | null {
        return `ALTER TABLE ${this.quote(table.name)} RENAME COLUMN ${this.quote(oldName)} TO ${this.quote(newCol.name)}`;
    }

    public renderReplaceView(view: JsonView, _ctx: DialectContext): string {
        const body = view.select.trim();
        if (!body) {return `-- view ${view.name} has empty body`;}
        if (view.materialized) {
            /*
             * Postgres has no CREATE OR REPLACE for materialized views —
             * drop and recreate. Emitted as a chained DDL so the executor
             * runs both halves in one exec() call.
             */
            return `DROP MATERIALIZED VIEW IF EXISTS ${this.quote(view.name)};\n`
                + `CREATE MATERIALIZED VIEW ${this.quote(view.name)} AS\n${body}`;
        }
        return `CREATE OR REPLACE VIEW ${this.quote(view.name)} AS\n${body}`;
    }

    public renderCreateRoutine(routine: JsonRoutine, _ctx: DialectContext): string | null {
        const body = routine.body.trim();
        if (!body) {return null;}
        /*
         * Postgres routines self-quote their body with dollar-quoting
         * (`$$ … $$`). We emit the user's body verbatim — they own the
         * dialect-specific syntax. No DELIMITER swap needed; pg's parser
         * handles dollar-quoted blocks natively.
         */
        return body;
    }

    public renderDropRoutine(routine: JsonRoutine, _ctx: DialectContext): string | null {
        const kind = String(routine.kind || '').toLowerCase();
        switch (kind) {
            case JsonRoutineKind.procedure: return `DROP PROCEDURE IF EXISTS ${this.quote(routine.name)}`;
            case JsonRoutineKind.function:  return `DROP FUNCTION IF EXISTS ${this.quote(routine.name)}`;
            /* Postgres triggers belong to a table, not a schema; the user names them with the table embedded so we can't always know the binding. */
            case JsonRoutineKind.trigger:   return `-- DROP TRIGGER ${routine.name} ON <table> — edit manually`;
            default: return `DROP ROUTINE IF EXISTS ${this.quote(routine.name)}`;
        }
    }

}