import {describe, expect, it} from 'vitest';
import {PostgresDialect} from '../../DbGenerator/Dialects/PostgresDialect.js';
import {DialectContext} from '../../DbGenerator/DbDialect.js';
import {buildDialectContextFromModel} from '../../DbGenerator/DialectContextBuilder.js';
import {
    JsonColumn,
    JsonDataDB,
    JsonDataDBType,
    JsonEnum,
    JsonForeignKey,
    JsonIndex,
    JsonIndexType,
    JsonTable,
    JsonTableOptions,
    JsonView
} from '../../DbEditor/JsonData.js';

const col = (name: string, patch: Partial<JsonColumn> = {}): JsonColumn => ({
    unid: `col-${name}`,
    name: name,
    type: 'int',
    ...patch
});

const table = (
    name: string,
    columns: JsonColumn[],
    patch: Partial<JsonTable> = {}
): JsonTable => ({
    unid: `tbl-${name}`,
    name: name,
    pos: {x: 0, y: 0},
    columns: columns,
    indexes: [],
    foreignKeys: [],
    options: undefined,
    ...patch
});

const db = (tables: JsonTable[], enums: JsonEnum[] = []): JsonDataDB => ({
    unid: 'db-test',
    name: 'test',
    type: JsonDataDBType.database,
    entrys: [],
    tables: tables,
    views: [],
    enums: enums
});

const ctxFor = (tables: JsonTable[], enums: JsonEnum[] = []): DialectContext =>
    buildDialectContextFromModel(db(tables, enums), '    ', ';', true);

describe('PostgresDialect.quote', () => {

    const d = new PostgresDialect();

    it('wraps identifier in double quotes', () => {
        expect(d.quote('users')).toBe('"users"');
    });

    it('doubles existing double quotes', () => {
        expect(d.quote('a"b')).toBe('"a""b"');
    });

});

describe('PostgresDialect.mapColumnType', () => {

    const d = new PostgresDialect();
    const ctx = ctxFor([]);

    it('collapses MySQL text variants onto TEXT', () => {
        expect(d.mapColumnType(col('c', {type: 'tinytext'}), ctx)).toBe('TEXT');
        expect(d.mapColumnType(col('c', {type: 'mediumtext'}), ctx)).toBe('TEXT');
        expect(d.mapColumnType(col('c', {type: 'longtext'}), ctx)).toBe('TEXT');
        expect(d.mapColumnType(col('c', {type: 'text'}), ctx)).toBe('TEXT');
    });

    it('renders BOOLEAN / JSONB / UUID / BYTEA / DOUBLE PRECISION', () => {
        expect(d.mapColumnType(col('c', {type: 'bool'}), ctx)).toBe('BOOLEAN');
        expect(d.mapColumnType(col('c', {type: 'json'}), ctx)).toBe('JSONB');
        expect(d.mapColumnType(col('c', {type: 'uuid'}), ctx)).toBe('UUID');
        expect(d.mapColumnType(col('c', {type: 'binary'}), ctx)).toBe('BYTEA');
        expect(d.mapColumnType(col('c', {type: 'blob'}), ctx)).toBe('BYTEA');
        expect(d.mapColumnType(col('c', {type: 'double'}), ctx)).toBe('DOUBLE PRECISION');
    });

    it('renders varchar with default length and decimal with default precision', () => {
        expect(d.mapColumnType(col('c', {type: 'varchar'}), ctx)).toBe('VARCHAR(255)');
        expect(d.mapColumnType(col('c', {type: 'decimal'}), ctx)).toBe('NUMERIC(10,0)');
        expect(d.mapColumnType(col('c', {type: 'decimal', length: '8,2'}), ctx)).toBe('NUMERIC(8,2)');
    });

    it('maps small/int/big to SMALLINT/INTEGER/BIGINT (no length suffix)', () => {
        expect(d.mapColumnType(col('c', {type: 'tinyint'}), ctx)).toBe('SMALLINT');
        expect(d.mapColumnType(col('c', {type: 'int', length: '11'}), ctx)).toBe('INTEGER');
        expect(d.mapColumnType(col('c', {type: 'bigint'}), ctx)).toBe('BIGINT');
    });

    it('resolves enum column types to the quoted enum name', () => {
        const e: JsonEnum = {
            unid: 'enum-status',
            name: 'status_enum',
            pos: {x: 0, y: 0},
            values: [{unid: 'v1', value: 'active'}]
        };
        const c = col('status', {type: 'enum', enumRef: 'enum-status'});
        expect(d.mapColumnType(c, ctxFor([], [e]))).toBe('"status_enum"');
    });

    it('falls back to TEXT for enum without resolvable type', () => {
        expect(d.mapColumnType(col('c', {type: 'enum'}), ctx)).toBe('TEXT');
        expect(d.mapColumnType(col('c', {type: 'enum', enumRef: 'missing'}), ctx)).toBe('TEXT');
    });

});

describe('PostgresDialect.renderCreateTable', () => {

    const d = new PostgresDialect();

    it('emits IDENTITY for auto-increment + PRIMARY KEY line', () => {
        const t = table('users', [
            col('id', {type: 'bigint', primaryKey: true, notNull: true, autoIncrement: true}),
            col('email', {type: 'varchar', length: '255', notNull: true})
        ]);
        const sql = d.renderCreateTable(t, ctxFor([t]));
        expect(sql).toContain('CREATE TABLE "users" (');
        expect(sql).toContain('"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY');
        expect(sql).toContain('"email" VARCHAR(255) NOT NULL');
        expect(sql).toContain('PRIMARY KEY ("id")');
    });

    it('emits no engine/charset; uses persistence + tablespace if present', () => {
        const opts: JsonTableOptions = {persistence: 'UNLOGGED', tablespace: 'fast_disk'};
        const t = table('t', [col('id', {primaryKey: true})], {options: opts});
        const sql = d.renderCreateTable(t, ctxFor([t]));
        expect(sql).toContain('CREATE UNLOGGED TABLE "t"');
        expect(sql).toContain('TABLESPACE "fast_disk"');
        expect(sql).not.toContain('ENGINE');
        expect(sql).not.toContain('CHARSET');
    });

    it('drops default when autoIncrement is set (covered by IDENTITY)', () => {
        const t = table('t', [
            col('id', {type: 'int', primaryKey: true, autoIncrement: true, defaultValue: '0'})
        ]);
        const sql = d.renderCreateTable(t, ctxFor([t]));
        expect(sql).not.toContain('DEFAULT 0');
    });

});

describe('PostgresDialect.renderCreateIndex', () => {

    const d = new PostgresDialect();

    it('renders a plain B-tree index', () => {
        const t = table('users', [col('email')]);
        const ix: JsonIndex = {
            unid: 'i1',
            name: 'idx_email',
            type: JsonIndexType.index,
            columns: [{columnUnid: 'col-email'}]
        };
        expect(d.renderCreateIndex(t, ix, ctxFor([t])))
        .toBe('CREATE INDEX "idx_email" ON "users" ("email")');
    });

    it('renders a unique index', () => {
        const t = table('users', [col('email')]);
        const ix: JsonIndex = {
            unid: 'i1',
            name: 'uq_email',
            type: JsonIndexType.unique,
            columns: [{columnUnid: 'col-email'}]
        };
        expect(d.renderCreateIndex(t, ix, ctxFor([t])))
        .toBe('CREATE UNIQUE INDEX "uq_email" ON "users" ("email")');
    });

    it('renders fulltext as USING GIN and spatial as USING GIST', () => {
        const t = table('docs', [col('body')]);
        const gin: JsonIndex = {unid: 'i1', name: 'ft', type: JsonIndexType.fulltext, columns: [{columnUnid: 'col-body'}]};
        const gist: JsonIndex = {unid: 'i2', name: 'sp', type: JsonIndexType.spatial, columns: [{columnUnid: 'col-body'}]};
        expect(d.renderCreateIndex(t, gin, ctxFor([t])))
        .toBe('CREATE INDEX "ft" ON "docs" USING GIN ("body")');
        expect(d.renderCreateIndex(t, gist, ctxFor([t])))
        .toBe('CREATE INDEX "sp" ON "docs" USING GIST ("body")');
    });

    it('emits DESC and partial WHERE', () => {
        const t = table('t', [col('a')]);
        const ix: JsonIndex = {
            unid: 'i1',
            name: 'p',
            type: JsonIndexType.index,
            columns: [{columnUnid: 'col-a', order: 'DESC'}],
            where: 'deleted_at IS NULL'
        };
        expect(d.renderCreateIndex(t, ix, ctxFor([t])))
        .toBe('CREATE INDEX "p" ON "t" ("a" DESC) WHERE deleted_at IS NULL');
    });

});

describe('PostgresDialect.renderAddForeignKey', () => {

    const d = new PostgresDialect();

    it('emits ALTER TABLE ADD CONSTRAINT FK', () => {
        const users = table('users', [col('id', {primaryKey: true})]);
        const orders = table('orders', [col('user_id')]);
        const fk: JsonForeignKey = {
            unid: 'fk1',
            name: 'fk_user',
            refTableUnid: 'tbl-users',
            columns: [{columnUnid: 'col-user_id', refColumnUnid: 'col-id'}],
            onDelete: 'CASCADE'
        };
        const sql = d.renderAddForeignKey(orders, fk, ctxFor([users, orders]));
        expect(sql).toBe(
            'ALTER TABLE "orders" ADD CONSTRAINT "fk_user" ' +
            'FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE'
        );
    });

});

describe('PostgresDialect.renderCreateEnum / renderDropEnum', () => {

    const d = new PostgresDialect();

    it('renders CREATE TYPE ... AS ENUM (...)', () => {
        const e: JsonEnum = {
            unid: 'e',
            name: 'status',
            pos: {x: 0, y: 0},
            values: [{unid: 'v1', value: 'a'}, {unid: 'v2', value: 'with\'quote'}]
        };
        expect(d.renderCreateEnum(e, ctxFor([])))
        .toBe('CREATE TYPE "status" AS ENUM (\'a\', \'with\'\'quote\')');
    });

    it('returns null for empty enum', () => {
        const e: JsonEnum = {unid: 'e', name: 'empty', pos: {x: 0, y: 0}, values: []};
        expect(d.renderCreateEnum(e, ctxFor([]))).toBeNull();
    });

    it('renders DROP TYPE IF EXISTS', () => {
        const e: JsonEnum = {unid: 'e', name: 'status', pos: {x: 0, y: 0}, values: []};
        expect(d.renderDropEnum(e, ctxFor([]))).toBe('DROP TYPE IF EXISTS "status"');
    });

});

describe('PostgresDialect drop renderers', () => {

    const d = new PostgresDialect();

    it('DROP TABLE … CASCADE', () => {
        const t = table('users', [col('id')]);
        expect(d.renderDropTable(t, ctxFor([t]))).toBe('DROP TABLE IF EXISTS "users" CASCADE');
    });

    it('DROP INDEX (no ON … needed in pg)', () => {
        const t = table('users', [col('email')]);
        const ix: JsonIndex = {
            unid: 'i',
            name: 'idx_email',
            type: JsonIndexType.index,
            columns: [{columnUnid: 'col-email'}]
        };
        expect(d.renderDropIndex(t, ix, ctxFor([t]))).toBe('DROP INDEX IF EXISTS "idx_email"');
    });

});

describe('PostgresDialect view renderers', () => {

    const d = new PostgresDialect();

    const view = (select: string, materialized = false): JsonView => ({
        unid: 'v',
        name: 'v_active',
        pos: {x: 0, y: 0},
        select: select,
        materialized: materialized
    });

    it('emits CREATE OR REPLACE VIEW for non-materialized', () => {
        const sql = d.renderCreateView(view('SELECT 1'), ctxFor([]));
        expect(sql).toBe('CREATE OR REPLACE VIEW "v_active" AS\nSELECT 1');
    });

    it('emits CREATE MATERIALIZED VIEW IF NOT EXISTS for materialized', () => {
        const sql = d.renderCreateView(view('SELECT 1', true), ctxFor([]));
        expect(sql).toBe('CREATE MATERIALIZED VIEW IF NOT EXISTS "v_active" AS\nSELECT 1');
    });

    it('renderReplaceView replaces non-materialized with CREATE OR REPLACE', () => {
        expect(d.renderReplaceView(view('SELECT 9'), ctxFor([])))
        .toBe('CREATE OR REPLACE VIEW "v_active" AS\nSELECT 9');
    });

    it('renderReplaceView drops-and-recreates materialized views', () => {
        const sql = d.renderReplaceView(view('SELECT 9', true), ctxFor([]));
        expect(sql).toContain('DROP MATERIALIZED VIEW IF EXISTS "v_active"');
        expect(sql).toContain('CREATE MATERIALIZED VIEW "v_active" AS\nSELECT 9');
    });

    it('DROP MATERIALIZED VIEW vs DROP VIEW based on flag', () => {
        expect(d.renderDropView(view('SELECT 1'), ctxFor([]))).toBe('DROP VIEW IF EXISTS "v_active"');
        expect(d.renderDropView(view('SELECT 1', true), ctxFor([]))).toBe('DROP MATERIALIZED VIEW IF EXISTS "v_active"');
    });

});

describe('PostgresDialect ALTER renderers (sync path)', () => {

    const d = new PostgresDialect();

    it('renders ADD COLUMN', () => {
        const t = table('users', [col('email', {type: 'varchar', length: '255', notNull: true})]);
        expect(d.renderAlterTableAddColumn(t, t.columns[0], ctxFor([t])))
        .toBe('ALTER TABLE "users" ADD COLUMN "email" VARCHAR(255) NOT NULL');
    });

    it('renders DROP COLUMN', () => {
        const t = table('users', [col('email')]);
        expect(d.renderAlterTableDropColumn(t, t.columns[0], ctxFor([t])))
        .toBe('ALTER TABLE "users" DROP COLUMN "email"');
    });

    it('emits SET DATA TYPE only when type/length differs', () => {
        const oldCol = col('email', {type: 'varchar', length: '64', notNull: true});
        const newCol = col('email', {type: 'varchar', length: '255', notNull: true});
        const t = table('users', [newCol]);
        const sql = d.renderAlterTableChangeColumn(t, oldCol, newCol, ctxFor([t]));
        expect(sql).toContain('SET DATA TYPE VARCHAR(255) USING "email"::VARCHAR(255)');
        expect(sql).not.toContain('DROP DEFAULT');
        expect(sql).not.toContain('NOT NULL');
    });

    it('emits SET DEFAULT when default value changes', () => {
        const oldCol = col('flag', {type: 'int'});
        const newCol = col('flag', {type: 'int', defaultValue: '0'});
        const t = table('t', [newCol]);
        const sql = d.renderAlterTableChangeColumn(t, oldCol, newCol, ctxFor([t]));
        expect(sql).toBe('ALTER TABLE "t" ALTER COLUMN "flag" SET DEFAULT 0');
    });

    it('emits DROP DEFAULT when old had default and new does not', () => {
        const oldCol = col('flag', {type: 'int', defaultValue: '0'});
        const newCol = col('flag', {type: 'int'});
        const t = table('t', [newCol]);
        const sql = d.renderAlterTableChangeColumn(t, oldCol, newCol, ctxFor([t]));
        expect(sql).toBe('ALTER TABLE "t" ALTER COLUMN "flag" DROP DEFAULT');
    });

    it('emits SET NOT NULL / DROP NOT NULL on nullability flip', () => {
        const t = table('t', [col('x')]);
        const setNN = d.renderAlterTableChangeColumn(t, col('x', {notNull: false}), col('x', {notNull: true}), ctxFor([t]));
        expect(setNN).toBe('ALTER TABLE "t" ALTER COLUMN "x" SET NOT NULL');
        const dropNN = d.renderAlterTableChangeColumn(t, col('x', {notNull: true}), col('x', {notNull: false}), ctxFor([t]));
        expect(dropNN).toBe('ALTER TABLE "t" ALTER COLUMN "x" DROP NOT NULL');
    });

    it('combines multiple actions in one ALTER TABLE', () => {
        const oldCol = col('x', {type: 'varchar', length: '64', notNull: false});
        const newCol = col('x', {type: 'varchar', length: '255', notNull: true, defaultValue: '\'foo\''});
        const t = table('t', [newCol]);
        const sql = d.renderAlterTableChangeColumn(t, oldCol, newCol, ctxFor([t]));
        expect(sql).toContain('SET DATA TYPE VARCHAR(255)');
        expect(sql).toContain('SET DEFAULT \'foo\'');
        expect(sql).toContain('SET NOT NULL');
        /* one statement, comma-separated actions */
        expect(sql.match(/ALTER TABLE/gu)?.length).toBe(1);
    });

    it('renders DROP CONSTRAINT (not DROP FOREIGN KEY) for the FK drop path', () => {
        const t = table('orders', [col('user_id')]);
        expect(d.renderDropForeignKey(t, 'fk_user', ctxFor([t])))
        .toBe('ALTER TABLE "orders" DROP CONSTRAINT "fk_user"');
    });

    it('renderAlterTableOptions returns null when no postgres-relevant option set', () => {
        const t = table('t', [col('id')], {options: {engine: 'InnoDB', charset: 'utf8'}});
        expect(d.renderAlterTableOptions(t, ctxFor([t]))).toBeNull();
    });

    it('renderAlterTableOptions emits SET TABLESPACE / SET UNLOGGED', () => {
        const t = table('t', [col('id')], {options: {tablespace: 'fast', persistence: 'UNLOGGED'}});
        expect(d.renderAlterTableOptions(t, ctxFor([t])))
        .toBe('ALTER TABLE "t" SET TABLESPACE "fast", SET UNLOGGED');
    });

    it('renderAlterTableOptions chains COMMENT ON TABLE as a separate statement', () => {
        const t = table('t', [col('id')], {options: {comment: 'core'}});
        const sql = d.renderAlterTableOptions(t, ctxFor([t]));
        expect(sql).toBe('COMMENT ON TABLE "t" IS \'core\'');

        const both = table('t', [col('id')], {options: {tablespace: 'fast', comment: 'core'}});
        const chained = d.renderAlterTableOptions(both, ctxFor([both]));
        expect(chained).toBe('ALTER TABLE "t" SET TABLESPACE "fast"; COMMENT ON TABLE "t" IS \'core\'');
    });

});