import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import {DbProject} from '../DbProject/DbProject.js';
import {JsonDataDB} from '../DbEditor/JsonData.js';
import {SchemaDiff} from '../DbDiff/SchemaDiff.js';
import {SyncGenerator, SyncStatement} from '../DbGenerator/Sync/SyncGenerator.js';
import {DbDialect, DialectContext} from '../DbGenerator/DbDialect.js';
import {SchemaChange, SchemaChangeKind} from '../DbDiff/ChangeTypes.js';

export type MigrationPair = {
    up: string;
    down: string;
};

const ensureDir = (dir: string): void => {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, {recursive: true});
    }
};

const timestamp = (now: Date): string =>
    now.toISOString().replace(/[-:T]/gu, '').slice(0, 14);

const shortHash = (text: string): string =>
    crypto.createHash('sha1').update(text).digest('hex').slice(0, 8);

/**
 * Build a stable identity key for a change that survives the random unid
 * assigned by `SchemaDiff.diff()`. Two diffs run back-to-back over the same
 * schema will produce different ids, so for the down-diff pairing we match
 * on (kind + tableName + columnName/indexName/fkName/viewName).
 *
 * For columnChanged / indexChanged / fkChanged / tableOptionsChanged the
 * pair we want is the *reverse* operation, which under SchemaDiff produces
 * the same kind on the swapped sides — so the key matches automatically.
 *
 * For symmetric pairs we map added↔dropped: a tableAdded in the forward
 * direction is a tableDropped in the reverse, so we treat them as one
 * identity bucket.
 */
const symmetricKind = (k: SchemaChangeKind): SchemaChangeKind => {
    switch (k) {
        case SchemaChangeKind.tableAdded: return SchemaChangeKind.tableDropped;
        case SchemaChangeKind.tableDropped: return SchemaChangeKind.tableAdded;
        case SchemaChangeKind.columnAdded: return SchemaChangeKind.columnDropped;
        case SchemaChangeKind.columnDropped: return SchemaChangeKind.columnAdded;
        case SchemaChangeKind.indexAdded: return SchemaChangeKind.indexDropped;
        case SchemaChangeKind.indexDropped: return SchemaChangeKind.indexAdded;
        case SchemaChangeKind.fkAdded: return SchemaChangeKind.fkDropped;
        case SchemaChangeKind.fkDropped: return SchemaChangeKind.fkAdded;
        case SchemaChangeKind.viewAdded: return SchemaChangeKind.viewDropped;
        case SchemaChangeKind.viewDropped: return SchemaChangeKind.viewAdded;
        default: return k;
    }
};

const identityKey = (c: SchemaChange): string => {
    const k = symmetricKind(c.kind);
    /*
     * Canonical kind = lexicographically lower of (forward, symmetric). For
     * the symmetric pairs (added↔dropped) this collapses both directions
     * onto the same bucket; for self-symmetric kinds (changed/options) k
     * equals c.kind already.
     */
    const canonical = c.kind < k ? c.kind : k;
    const parts = [
        canonical,
        c.tableName ?? '',
        c.columnName ?? '',
        c.indexName ?? '',
        c.fkName ?? '',
        c.viewName ?? ''
    ];
    return parts.join('|');
};

/**
 * Reverse-diff helper: given the forward changeIds and the model/live DB
 * trees, run `SchemaDiff.diff(live, model, ...)` (swapped) to produce the
 * inverse SQL, then keep only those reverse-changes whose identity key
 * matches a forward-applied change.
 */
const renderInverseStatements = (
    forwardChanges: SchemaChange[],
    modelDb: JsonDataDB,
    liveDb: JsonDataDB,
    sync: {ignoreTables: string[]; ignoreColumnAttributes: string[];},
    dialect: DbDialect,
    ctx: DialectContext,
    modelRoot: JsonDataDB
): SyncStatement[] => {
    /*
     * Reverse direction: pretend the live DB is the model and the model is
     * the live state. The resulting change-set is what we'd need to "undo"
     * the forward changes.
     */
    const inverse = SchemaDiff.diff(liveDb, modelDb, sync, modelRoot);
    const wanted = new Set(forwardChanges.map(identityKey));
    inverse.changes = inverse.changes.filter(c => wanted.has(identityKey(c)));
    /*
     * The inverse SchemaDiff resolved tables off the live tree, but
     * SyncGenerator renders against tables it can look up by name in the
     * supplied `modelDb` arg. Pass the live tree so `tableFor` lookups
     * resolve in the inverse-direction too.
     */
    return SyncGenerator.generate(inverse, liveDb, dialect, ctx);
};

const joinStatements = (statements: SyncStatement[], terminator: string): string =>
    statements.map(s => s.sql + terminator).join('\n\n');

const fileHeader = (project: DbProject, subject: string): string => {
    if (!project.output.sqlComment) {return '';}
    return `-- generated by dbeditor sync — ${subject}\n-- dialect: ${project.dialect}\n\n`;
};

/**
 * Writes a forward/reverse migration pair for the changes that were just
 * applied. Filenames follow `<timestamp>__sync_<hash>.up.sql` /
 * `.down.sql` and land in `project.output.destinationPath`.
 *
 * Returns the two file paths so callers can echo them back to the UI.
 * The directory is created if missing; existing files are *not* removed
 * — each sync gets its own timestamped pair.
 */
export class MigrationPairWriter {

    public static write(
        project: DbProject,
        modelDb: JsonDataDB,
        liveDb: JsonDataDB,
        modelRoot: JsonDataDB,
        forwardChanges: SchemaChange[],
        forwardStatements: SyncStatement[],
        dialect: DbDialect,
        ctx: DialectContext
    ): MigrationPair {
        const dest = project.output.destinationPath;
        ensureDir(dest);

        const term = project.output.statementTerminator || ';';
        const upBody = joinStatements(forwardStatements, term);
        const inverse = renderInverseStatements(forwardChanges, modelDb, liveDb, project.sync, dialect, ctx, modelRoot);
        const downBody = joinStatements(inverse, term);

        const hash = shortHash(upBody);
        const ts = timestamp(new Date());
        const baseName = `${ts}__sync_${hash}`;

        const upPath = path.join(dest, `${baseName}.up.sql`);
        const downPath = path.join(dest, `${baseName}.down.sql`);
        fs.writeFileSync(upPath, `${fileHeader(project, `sync up — ${baseName}`)}${upBody}\n`);
        fs.writeFileSync(downPath, `${fileHeader(project, `sync down — ${baseName}`)}${downBody}\n`);

        return {up: upPath, down: downPath};
    }

}